#!/usr/bin/env bash
BASE_DIR=$(dirname `which $0`)
echo $BASE_DIR
export AWESOME_CONFIG=$BASE_DIR
export AWESOME_LUA_PATH="$BASE_DIR/lua/?.lua;$BASE_DIR/msgpack/?.lua;"
eval $(luarocks --lua-version 5.3 path)
awesome -c $BASE_DIR/rc.lua 2>/tmp/awesome-err.log 1>/tmp/awesome.log
